export enum ClassStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    UNDER_REVISION = 'UNDER_REVISION',
    LOCKED = 'LOCKED',
    DELETED = 'DELETED',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED'
  }
  